{% set name = "ConcurrentLogHandler" %}
{% set version = "0.9.19" %}

package:
  name: {{ name.lower() }}
  version: {{ version }}

build:
  number: 0

requirements:
  run:
    - concurrent-log-handler

test:
  imports:
    - cloghandler

about:
  home: https://launchpad.net/python-concurrent-log-handler
  license: Apache-2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Shim redirecting to concurrent-log-handler
extra:
  recipe-maintainers:
    - mariusvniekerk
