travis:
  secure:
    BINSTAR_TOKEN: KF40cp0N6K0ARbAZFUEVWF6J3Ip7vAlru94/TTy/ZhlpeeqdzTkRsz94lRskM0pv15qpt37SPNvqCcw5dvIG61wvdkDkuIe+byDY9RdVua7L7CX/8eRZ4wZbyp1FCd79jwoPLk8r2FehuIKLrooCaq45MsHy8Zv43sRYuRUeiO2+tI4WM1M0eKtrwr9uOsv4fkdjQ9P1RuUEAdSh6d5l2fBzOXhMJso6GGwm7ntMSu9uJX88zaGQ/wri3ZqiaTTTRCbTaMOmn6LQjvzeTRfozG7gfCpeSmckNXBSyw6cEbO5s/jFGnIB6J5vSUPoWM+eeE6S7Ypd1QnSyH/IcLj9MwtOgxbMznaqPmJ/7FL2xTAU42/NN83vfCa1mFXBGlkHc2zok0PLq537x46i8IjIK+4VtDwOnTjw45RzHSmX9IZR1YZGgYhrVOiKZ6tuYk9XFdmfdmbBM1+TLcRzLLvBDQZ7kRdLsPrdbg6tk6lWIMhZ52WWvQduT4DXHsq2UX5owDce3LBByf+vVZC88hEvmEjC5WeVRaFBs/5N4XHAtqqxAiy5LL6TTRGv6OhG73DghAcJFjqPVQlBtDlZQPjbCIpNJ9T2XonSUuL8zFW4Qy9Nt2ar9FDs8IA3floI5OOJRZIFSvpfaQPz8ATK+9CM0x2UgqaNZqLqep1kmghCkb4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
