travis:
  secure:
    BINSTAR_TOKEN: FcpFR0Aft5opIr3Ey8Gtoyc1a4gTvXo4etK6dBsg6eMKldDC5tvbd/c1S8LmwgkK1f1AbSf39MnJQCXdBsKHvXhYIed2x5hf6COntljoySYXC6kwbHOE2hy2hVnbFL+9bP3pb2iXqulDfcNfUcbu4bh+l0Sm4mf5gCigiygVGs0gZg8/krO0sfjy7nh+MSyeaYoAwQr3E6w84aHRkN+3RE53Nk/RwEzVxl7dgkqW0FXdHajK8k0hMJg5gpb8RLHFz5Ts1HpwwJPNf0zz729t1FZIpMte7voeIf81OuRP2Ihj9+3QokCpi1bC4yo4p3lksUlzo+flZp88KXLhoamppn1OOUUtYsHQp5iloMHOMOvN3nVf92fSQGLVf/id7E+0Gsv04YJbwgpQ6/ar0FEe4Gm/rmE1qdAqRqG9HVkdgC2j7/0sjqLvq1CQHbvKflqje5cU3a3bTNle/Od9XO6MKoFDMmc9IfECmEJou5XQgscVOXDhEBhacGp8qMtnTvu3C8oTuKXEY/gBmkyspducPdoeLs6mxQCUN12+gQ0/FXf1nqhotXUmqkIA9w9xhYMXxlNvVV/Hj+pHVif1csUpUIRximUp2jiEVaU+OyWgkGf/E842RaEArdyhr2EZYzKmr0qp/1vOsU7jNrlhQ0MRd8hSqXwwsQExC5/yq5IYN3c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
